### ISSUE TITLE
Use the Scheduler library

### ISSUE THREAD

**Issue by lebeno** [timelab/ADEM#3]
We could use the Scheduler library to create separate "threads":
- sendBuffer()
- GPS data reading and processing
- analog sampling of dust sensor

**Comment by lebeno** [comment]
kavers1 is working on a scheduling library

**Comment by kavers1** [comment]
First version is available. Although it may crash when turning logging on, it functioned well for over 12 hours when just doing its job. Need further testing but is ready for initial use and keep the project going.

**Comment by dagwieers** [comment]
@kavers1 @lebeno We are having issues using SoftwareSerial (GPS) together with interrupt handlers for the PPD42.I assume that when we are receiving GPS data interrupts for PPD42 are disabled ? We always get 0 (both for PM10 as PM25). It only works if we stop using SoftwareSerial.
- Do we plan to use the real UART for the communication with the GPS ? (And Pin2 for debugging, and move i2c CLS to another pin)
- Or can we make use on an i2c-based GPS module instead (e.g. http://uk.farnell.com/gps-modules/module-interface/i2c-spi-uart/pg/110161246) ?

**Comment by dagwieers** [comment]
We can close this issue. The TickerSchedlr is integrated in the main code now.
Next step is to implement the pseudo-code using TickerSchedlr.
