### ISSUE TITLE
Create Github organization and team

### ISSUE THREAD

**Issue by lebeno** [timelab/ADEM#6]
The ADEM repository is currently under my personal github account. It would be nice to create a github "timelab" organization and an "ADEM" team in github. Unfortunately @timelab is already taken.

**Comment by lebeno** [comment]
It possible, could user @timelab contact me to clarify if he/she is in any way connected to http://timelab.org, the Fablab active in Ghent, Belgium?

**Comment by dagwieers** [comment]
I opened a question to Github to see what is possible. Either have them contact the user to clarify the situation, or free the account so it can be used by Timelab. I doubt the notifications are going anywhere...

**Comment by dagwieers** [comment]
@lebeno Can you please unfollow him ? So it correctly appears the account is stale and unused.

**Comment by lebeno** [comment]
done -> 0 followers

**Comment by lebeno** [comment]
Thanks to Arnaud, Evi and Dag the timelab github account/organisation is a fact! I have transferred the ADEM repo from my personal account to the timelab organisation.
